#!/bin/sh

if [[ "$1" == "--android-sdk" ]]; then
	ANDROID_SDK="$2"
	shift; shift
fi

SIKULI_SCRIPT_JAR=lib/sikuli-script.jar
SIKULI_PLUGIN_JAR=lib/seemonkey.jar

CLASSPATH=$SIKULI_SCRIPT_JAR:$SIKULI_PLUGIN_JAR
CLASSPATH=${CLASSPATH}:$ANDROID_SDK/tools/lib/guavalib.jar
CLASSPATH=${CLASSPATH}:$ANDROID_SDK/tools/lib/monkeyrunner.jar
CLASSPATH=${CLASSPATH}:$ANDROID_SDK/tools/lib/sdklib.jar
CLASSPATH=${CLASSPATH}:$ANDROID_SDK/tools/lib/chimpchat.jar
CLASSPATH=${CLASSPATH}:$ANDROID_SDK/tools/lib/ddmlib.jar

#emulator -avd Gingerbread -no-boot-anim &

# NOT FOR DEPLOYMENT -- TEST CODE
cp ~/Projects/SeeMonkey/example/*.jar ./lib/

java -cp $CLASSPATH org.sikuli.script.SikuliScript scripts/example.sm
